---
title: Are Cats Bad for the Environment?
id: 1617
peer_reviewed: false
url_is_not_publisher: false
url_is_direct_link_to_full_text: true
url: https://www.motherjones.com/environment/2011/07/cats-tnr-birds-feral/#apocalypse_meow
publication_title: Mother Jones
published_date: 
authors: []
kind: article
quotes: []
