---
title: Overall, the case for reduced meat consumption is strong. Vegetarianism is
  cheaper, better for your health (if you can afford a diverse diet and are not an
  infant), and is less impactful for the environment. It also has a significant moral
  cost in terms of animal suffering
id: '33'
cited_urls:
- url: https://slatestarcodex.com/2019/12/11/acc-is-eating-meat-a-net-harm
  quotes: []
  challenges: 
new_cited_url: 
topics:
- Diet
- Environmentalism
- Health
- Vegetarianism
arguments:
  '1':
    id: 1
    text: "> Overall, the case for reduced meat consumption is strong. Vegetarianism
      is cheaper, better for your health (if you can afford a diverse diet and are
      not an infant), and is less impactful for the environment. It also has a significant
      moral cost in terms of animal suffering."
    quote_urls:
    - https://slatestarcodex.com/2019/12/11/acc-is-eating-meat-a-net-harm
